### PR TITLE
Play 2 sample

### PR DESCRIPTION
**Pull request by julienrf**
This patch adds a test for the [Play 2](https://github.com/playframework/Play20) framework.

### CODE REVIEW

**Comment by julienrf** [comment]
FYI the simple Hello World test runs at 7k req/s on my Core 2 Duo 2.0 GHz.

**Comment by seedifferently** [comment]
This is a bit of a different animal than I'm used to. I'm assuming you don't run this through apache (as the other tests are setup)?

**Comment by julienrf** [comment]
You don’t need apache to run it. A JVM is enough.

Just clone the current [Play 2](https://github.com/playframework/Play20) source, go in the `framework/` directory and run the `./build` script. Then, run the `build-repository` command to compile the framework from sources.
(Ok, maybe I should use the current RC2 release, so you won’t have to compile the framework by yourself, you just download it et voilà)

**Comment by julienrf** [comment]
Do you intend to merge this pull request before your next release?

**Comment by seedifferently** [comment]
I'd like to. Since its GitHub page has >1000 watchers, I think it probably qualifies as a rather popular framework. It's just probably going to take a while for me to get the next refresh finished seeing as I seem to have so much to do!

**Comment by julienrf** [comment]
Can I help?

**Comment by seedifferently** [comment]
How good is your Python? Want to lend a hand to #26?

**Comment by kev009** [comment]
@julienrf can you change this to production mode?  The settings is in debug mode right now.

**Comment by julienrf** [comment]
@seedifferently Sure I can help you :) Did you start writing the fabric file?
@kev009 the `run` sbt command goes in dev mode, use the `start` sbt command to go in prod mode.

**Comment by seedifferently** [comment]
@julienrf no, not yet. would love the help.

**Pull request closed without merging**
