### PR TITLE
Complete Express version

### PR DESCRIPTION
**Pull request by naholyr**
Completed version based on the previous PR (based on Handlebars template engine, not my favorite but whatever :P).
- Don't forget to run `npm rebuild` to compile sqlite3.
- Server runs on port 8000, and URIs are `/`, `/hb_hello` and `/hb_sql`.

_update_: run `npm install` to retrieve (and eventually compile) required dependencies.

### CODE REVIEW

**Comment by seedifferently** [comment]
Thanks! Is there any way we can have this included without all the dependencies and just instruct anyone who wants to run the test to install the various components using npm? I'm including a pretty bare-bones setup in the other tests, so I'd prefer to keep it simple here as well.

**Comment by naholyr** [comment]
Oh sure, best practices are a matter of state for this question ;)
- Pros: no need to download dependencies when deploying (and here, we're talking about deployment, not about an external module being published), and the insurance that all server instances share the exact same version of modules (which could be nice here).
- Cons: huge commits hard to analyze (not cool for a public project), and the need to re-commit if you want newer versions of modules (but that could not be a cons here: we could compare more easily the before/after when upgrading a module).

Your turn now: I send another PR without the dependencies and you'll make your choice depending on this pros/cons ;)

**Comment by naholyr** [comment]
Oh sorry, Bad move I forgot Github could update PRs :-\ So you have only one version directly mergeable. If you want to finally keep the dependencies tell me and I'll update it again.

**Comment by seedifferently** [comment]
Just cherry-pick-merged in most of these commits. If you'd like to tinker with it a little more (in case I missed anything) please submit another request.

Thanks so much for your help! I'm looking forward to having a node.js based test in the benchmarks.

**Pull request closed without merging**
