### PR TITLE
Lithium App

### PR DESCRIPTION
**Pull request by cgarvis**
Created a Lithium (the project formerly known as Cake3) app based on the CakePHP version. 

https://github.com/UnionOfRAD/lithium

### CODE REVIEW

**Comment by seedifferently** [comment]
Christopher, 

Thanks so much! Can you please comment on Lithium's popularity? Is it widely used? Are there any big sites built on it?

**Comment by josegonzalez** [comment]
Lithium is widely used. Totsy is a site that uses it, and the 10gen folks seem to give lots of support to it.

**Comment by cgarvis** [comment]
gimmebar.com is another

**Comment by josegonzalez** [comment]
You might want to update your favicon.ico ;)

**Comment by seedifferently** [comment]
Merged into the dev branch @ bb59d12

**Pull request closed without merging**
