### PR TITLE
Nette Framework

### PR DESCRIPTION
**Pull request by Vrtak-CZ**
For test run use [Nette Framework](http://nette.org) sandbox from [this package](http://files.nette.org/releases/2.0/NetteFramework-2.0-PHP5.3.zip) and replace app dir.

If you need run "string" test with Presenter (Controler) remove `#` before `stringController: true` in _app/config/config.neon_ and clean cache (remove _temp/cache_). Default is a microframework way (route callback).

Documen Root is _www_ dir in sandbox.

### CODE REVIEW

**Comment by seedifferently** [comment]
Can you please comment on Nette's popularity? Is it widely used? Are there any big sites built on it?

**Comment by fprochazka** [comment]
Nette Framework is the most popular framework in Czech Republic. Sites with huge trafic are build on it. 

You can read here few examples, of who uses the framework http://nette.org/en/who-uses-nette-framework

Currently, we are trying to spread abroad Nette Framework more.

**Comment by NoxArt** [comment]
Nette is powering the by far most visited IMDB-like website in Czech Rep. (and possibly Slovak Rep. as well). If I get it right, last year's March they had 1.3M unique visitors.

As HosipLan also noted on IRC it's the core of the biggest discount site in the country, according to their site they have issued discounts worth $50M, so it should be highly visited and secured site.

**Comment by FrantisekSidak** [comment]
I am surprised on daily basis, how much Czech sites are running on nette, including sites with big traffic:
http://www.denik.cz/ (news)
http://uloz.to/ (biggest download server)
http://www.csfd.cz/ (imdb-like, see above)
etc.
(But, nette can be used for very small projects also (microframework ability)).

**Comment by obrejla** [comment]
Nette is really powerful framework. ApiGen (new documentation generator for PHP) is based on it and it's supported by new NetBeans release (instead of PHPDocumentor).

It would be really great to see it together with Rails, Django, etc.

**Comment by kukulich** [comment]
Is there anything more you need to merge this pull request?

**Comment by seedifferently** [comment]
I think everything looks good. Just have had other things on my plate. I will try to get this in soon.

**Pull request closed without merging**
