### PR TITLE
Updated CakePHP version

### PR DESCRIPTION
**Pull request by josegonzalez**
Your benchmark would be more useful with recent versions of the framework. Just helping out.

### CODE REVIEW

**Comment by seedifferently** [comment]
Thanks Jose!

I thought I might just leapfrog 2.0 and jump to 2.1 when it's released. I am planning an update across the board soon but am just waiting for a few releases (Django 1.4, Pyramid 1.3, CodeIgniter 2.1, etc).

**Comment by josegonzalez** [comment]
Same exact code will work in 2.1. No changes necessary. Just update your benchmarks when it comes out.

**Comment by seedifferently** [comment]
Great, thanks again!

**Comment by josegonzalez** [comment]
Hint, you can merge this pull request in.

**Comment by ryansnowden** [comment]
I'm quite happy with that Hint

**Comment by josegonzalez** [comment]
Will update the pull request tonight to fix the core.php to turn off all level of debugging, logging, etc.

**Comment by seedifferently** [comment]
If we're thinking "production mode" with these tests, wouldn't a certain level of logging still be enabled?

**Comment by ryansnowden** [comment]
Only during beta. PHP, Apache and MySQL provide the necessary. Logging gets turned on to get more info if needed.

**Comment by seedifferently** [comment]
Fair enough.

**Pull request closed without merging**
