### PR TITLE
Added FuelPHP APP

### PR DESCRIPTION
**Pull request by HellPat**
I added an App for FuelPHP http://fuelphp.com/
It uses dsn or orm

Call via:
/hello
/hellos
/hellodb
/helloorm

### CODE REVIEW

**Comment by seedifferently** [comment]
Thanks! I will try to get this into the next update.

**Comment by HellPat** [comment]
And what i forgot to say is that it was created with FuelPHP 1.1
FuelPHP is a very young Framework

**Comment by Savageman** [comment]
That's good I'm interested in the results for this one, thanks!

I would juste remove the 'orm' from config.always_load.packages, since it's not needed for 3 out of the 4 tests. You can just load it manually with `Pacakge::load('orm');` in `Controller_Helloorm->action_index()`

**Comment by HellPat** [comment]
You're right, ill do that.
This is in the standart-config, so i used it ;-)
It will slow down the app.

I never saw a benchmark from FuelPHP

**Comment by HellPat** [comment]
Damn, i wanted to push the comment button but missed :-)

**Comment by seedifferently** [comment]
Merged into the dev branch @ e7b1e03

**Pull request closed without merging**
