### PR TITLE
node.js

### PR DESCRIPTION
**Pull request by clneagu**
I added bare node.js & node.js + express + handlebars for the template version

### CODE REVIEW

**Comment by seedifferently** [comment]
Thanks! I will try to get this into the next update.

**Comment by ckihneman** [comment]
Nice work, I would love to see node.js in these results as well.

**Comment by seedifferently** [comment]
Seeing that this is a _web framework_ shootout, would express be the "framework" to test with node.js, or does node deserve it's own isolated setup?

**Comment by ckihneman** [comment]
I think you would be right to say express is the framework on node.js. As others might want to include [frameworks](https://github.com/joyent/node/wiki/modules#wiki-web-frameworks-full) like [Ace](https://github.com/maccman/ace) for node.js. Same would apply to templating, as you could choose to use any of the [various others out there](https://github.com/joyent/node/wiki/modules#wiki-templating).

**Comment by seedifferently** [comment]
Thanks @ckihneman, I am not very familiar with the node.js world so I am relying on you all's suggestions.

It does seem to be that express is quite the popular choice for node. Would handlebars be considered the most popular templating package, or would another be more appropriate?

**Comment by ckihneman** [comment]
I'd say @clneagu's implementation is fairly generic, and would be a great starting point for a node.js benchmark. Express and Handlebars have been in the wild for quite awhile and are widely used. I'm sure your coffeescripters looking at this might want to see [Eco](https://github.com/sstephenson/eco) as the templating choice. But i bet you could leave that to them :)

**Comment by seedifferently** [comment]
Great, how about somebody adding a sqlite the test in there for me?

**Pull request merged**
